// Code generated by protoc-gen-go. DO NOT EDIT.
// source: create_user.proto

package wechatd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                   string            `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	Username             string            `protobuf:"bytes,2,opt,name=Username" json:"Username,omitempty"`
	Extras               map[string]string `protobuf:"bytes,3,rep,name=extras" json:"extras,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_create_user_a97d7dd6c3f1ae0b, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetExtras() map[string]string {
	if m != nil {
		return m.Extras
	}
	return nil
}

type CreateUserRequest struct {
	Username             *wrappers.StringValue            `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password             *wrappers.StringValue            `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Extras               map[string]*wrappers.StringValue `protobuf:"bytes,3,rep,name=extras" json:"extras,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_create_user_a97d7dd6c3f1ae0b, []int{1}
}
func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(dst, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUsername() *wrappers.StringValue {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *CreateUserRequest) GetPassword() *wrappers.StringValue {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *CreateUserRequest) GetExtras() map[string]*wrappers.StringValue {
	if m != nil {
		return m.Extras
	}
	return nil
}

type CreateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_create_user_a97d7dd6c3f1ae0b, []int{2}
}
func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (dst *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(dst, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "ai.metathings_wechatd.service.wechatd.User")
	proto.RegisterMapType((map[string]string)(nil), "ai.metathings_wechatd.service.wechatd.User.ExtrasEntry")
	proto.RegisterType((*CreateUserRequest)(nil), "ai.metathings_wechatd.service.wechatd.CreateUserRequest")
	proto.RegisterMapType((map[string]*wrappers.StringValue)(nil), "ai.metathings_wechatd.service.wechatd.CreateUserRequest.ExtrasEntry")
	proto.RegisterType((*CreateUserResponse)(nil), "ai.metathings_wechatd.service.wechatd.CreateUserResponse")
}

func init() { proto.RegisterFile("create_user.proto", fileDescriptor_create_user_a97d7dd6c3f1ae0b) }

var fileDescriptor_create_user_a97d7dd6c3f1ae0b = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x69, 0x37, 0xc7, 0xcc, 0x40, 0x5c, 0xf0, 0x30, 0x8a, 0xc8, 0x18, 0x08, 0x03, 0x59,
	0x0a, 0x13, 0x74, 0x7a, 0xf1, 0xa0, 0x3b, 0xec, 0x24, 0x54, 0xa6, 0x17, 0x61, 0x64, 0xed, 0xb3,
	0x0b, 0x5b, 0x9b, 0x9a, 0xa4, 0xab, 0xfb, 0xe7, 0xf6, 0xb7, 0x49, 0xd2, 0x76, 0x14, 0x15, 0x36,
	0x6f, 0xef, 0xbd, 0xbe, 0xef, 0x7b, 0x5f, 0x7f, 0x41, 0x6d, 0x5f, 0x00, 0x55, 0x30, 0x4b, 0x25,
	0x08, 0x92, 0x08, 0xae, 0x38, 0xbe, 0xa4, 0x8c, 0x44, 0xa0, 0xa8, 0x5a, 0xb0, 0x38, 0x94, 0xb3,
	0x0c, 0xfc, 0x05, 0x55, 0x01, 0x91, 0x20, 0xd6, 0xcc, 0x07, 0x52, 0xf4, 0xce, 0x45, 0xc8, 0x79,
	0xb8, 0x02, 0xd7, 0x88, 0xe6, 0xe9, 0x87, 0x9b, 0x09, 0x9a, 0x24, 0x20, 0x64, 0x6e, 0xe3, 0xdc,
	0x84, 0x4c, 0x2d, 0xd2, 0x39, 0xf1, 0x79, 0xe4, 0x46, 0x19, 0x53, 0x4b, 0x9e, 0xb9, 0x21, 0x1f,
	0x98, 0x8f, 0x83, 0x35, 0x5d, 0xb1, 0x80, 0x2a, 0x2e, 0xa4, 0xbb, 0x2b, 0x73, 0x5d, 0x6f, 0x6b,
	0xa1, 0xfa, 0x54, 0x82, 0xc0, 0x27, 0xc8, 0x9e, 0x04, 0x1d, 0xab, 0x6b, 0xf5, 0x8f, 0x3d, 0x7b,
	0x12, 0x60, 0x07, 0x35, 0xf5, 0x3c, 0xa6, 0x11, 0x74, 0x6c, 0x33, 0xdd, 0xf5, 0xf8, 0x19, 0x35,
	0xe0, 0x4b, 0x09, 0x2a, 0x3b, 0xb5, 0x6e, 0xad, 0xdf, 0x1a, 0xde, 0x92, 0x83, 0x7e, 0x82, 0x68,
	0x03, 0x32, 0x36, 0xca, 0x71, 0xac, 0xc4, 0xc6, 0x2b, 0x6c, 0x9c, 0x3b, 0xd4, 0xaa, 0x8c, 0xf1,
	0x29, 0xaa, 0x2d, 0x61, 0x53, 0x84, 0xd1, 0x25, 0x3e, 0x43, 0x47, 0x6b, 0xba, 0x4a, 0xcb, 0x28,
	0x79, 0x73, 0x6f, 0x8f, 0xac, 0xde, 0xd6, 0x46, 0xed, 0x47, 0x43, 0x55, 0xbb, 0x7b, 0xf0, 0x99,
	0x82, 0x54, 0x78, 0x84, 0x9a, 0x69, 0x99, 0x5e, 0xdb, 0xb4, 0x86, 0xe7, 0x24, 0x27, 0x48, 0x4a,
	0x82, 0xe4, 0x45, 0x09, 0x16, 0x87, 0xaf, 0xda, 0xc9, 0xdb, 0x6d, 0x6b, 0x65, 0x42, 0xa5, 0xcc,
	0xb8, 0x08, 0xcc, 0xb1, 0xbd, 0xca, 0x72, 0x1b, 0xbf, 0xff, 0xa0, 0xf2, 0x74, 0x20, 0x95, 0x5f,
	0xe9, 0xff, 0x44, 0xf4, 0xb6, 0x0f, 0xd1, 0xb0, 0x8a, 0x68, 0x5f, 0xea, 0x0a, 0xc0, 0x29, 0xc2,
	0xd5, 0x04, 0x32, 0xe1, 0xb1, 0x04, 0xfc, 0x80, 0xea, 0x1a, 0x49, 0x01, 0xef, 0xea, 0x1f, 0x0f,
	0xec, 0x19, 0xe1, 0xbc, 0x61, 0xee, 0x5e, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xfd, 0x40,
	0x9e, 0xf3, 0x02, 0x00, 0x00,
}
