// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: create_user.proto

/*
Package wechatd is a generated protocol buffer package.

It is generated from these files:
	create_user.proto
	get_metathings_token.proto
	get_wechat_session.proto
	service.proto

It has these top-level messages:
	User
	CreateUserRequest
	CreateUserResponse
	GetMetathingsTokenRequest
	GetMetathingsTokenResponse
	GetWechatSessionRequest
	GetWechatSessionResponse
*/
package wechatd

import fmt "fmt"
import go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import math "math"
import _ "github.com/golang/protobuf/ptypes/wrappers"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *User) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *CreateUserRequest) Validate() error {
	if nil == this.Openid {
		return go_proto_validators.FieldError("Openid", fmt.Errorf("message must exist"))
	}
	if this.Openid != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Openid); err != nil {
			return go_proto_validators.FieldError("Openid", err)
		}
	}
	if this.Username != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Username); err != nil {
			return go_proto_validators.FieldError("Username", err)
		}
	}
	if this.Password != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Password); err != nil {
			return go_proto_validators.FieldError("Password", err)
		}
	}
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *CreateUserResponse) Validate() error {
	if this.User != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.User); err != nil {
			return go_proto_validators.FieldError("User", err)
		}
	}
	return nil
}
