// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: get_metathings_token.proto

/*
Package wechatd is a generated protocol buffer package.

It is generated from these files:
	get_metathings_token.proto
	get_wechat_session.proto
	service.proto

It has these top-level messages:
	GetMetathingsTokenRequest
	GetMetathingsTokenResponse
	GetWechatSessionRequest
	GetWechatSessionResponse
*/
package wechatd

import fmt "fmt"
import go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import math "math"
import _ "github.com/golang/protobuf/ptypes/wrappers"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *GetMetathingsTokenRequest) Validate() error {
	if nil == this.OpenId {
		return go_proto_validators.FieldError("OpenId", fmt.Errorf("message must exist"))
	}
	if this.OpenId != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.OpenId); err != nil {
			return go_proto_validators.FieldError("OpenId", err)
		}
	}
	return nil
}
func (this *GetMetathingsTokenResponse) Validate() error {
	return nil
}
