// Code generated by protoc-gen-go. DO NOT EDIT.
// source: get_token.proto

package wechatd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetTokenRequest struct {
	OpenId               *wrappers.StringValue `protobuf:"bytes,1,opt,name=open_id,json=openId" json:"open_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetTokenRequest) Reset()         { *m = GetTokenRequest{} }
func (m *GetTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenRequest) ProtoMessage()    {}
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_get_token_613a0bc1560a12af, []int{0}
}
func (m *GetTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenRequest.Unmarshal(m, b)
}
func (m *GetTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenRequest.Marshal(b, m, deterministic)
}
func (dst *GetTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenRequest.Merge(dst, src)
}
func (m *GetTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenRequest.Size(m)
}
func (m *GetTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenRequest proto.InternalMessageInfo

func (m *GetTokenRequest) GetOpenId() *wrappers.StringValue {
	if m != nil {
		return m.OpenId
	}
	return nil
}

type GetTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenResponse) Reset()         { *m = GetTokenResponse{} }
func (m *GetTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetTokenResponse) ProtoMessage()    {}
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_get_token_613a0bc1560a12af, []int{1}
}
func (m *GetTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenResponse.Unmarshal(m, b)
}
func (m *GetTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenResponse.Marshal(b, m, deterministic)
}
func (dst *GetTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenResponse.Merge(dst, src)
}
func (m *GetTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetTokenResponse.Size(m)
}
func (m *GetTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenResponse proto.InternalMessageInfo

func (m *GetTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*GetTokenRequest)(nil), "ai.metathings_wechatd.service.wechatd.GetTokenRequest")
	proto.RegisterType((*GetTokenResponse)(nil), "ai.metathings_wechatd.service.wechatd.GetTokenResponse")
}

func init() { proto.RegisterFile("get_token.proto", fileDescriptor_get_token_613a0bc1560a12af) }

var fileDescriptor_get_token_613a0bc1560a12af = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xa9, 0x60, 0xc7, 0xe2, 0x61, 0x52, 0x3c, 0xc8, 0x10, 0x1d, 0x03, 0x61, 0x97, 0x25,
	0xa0, 0xe0, 0xcd, 0xcb, 0x2e, 0xe2, 0x4d, 0xaa, 0x78, 0xf0, 0x52, 0xd2, 0xf6, 0x99, 0x3e, 0xd6,
	0xe6, 0xc5, 0xe4, 0x75, 0xfd, 0x73, 0x05, 0xff, 0x12, 0x59, 0x3a, 0xdd, 0x2d, 0x1f, 0xe1, 0xf7,
	0xfb, 0xde, 0x27, 0x66, 0x06, 0xb8, 0x60, 0xda, 0x82, 0x95, 0xce, 0x13, 0x53, 0x76, 0xab, 0x51,
	0x76, 0xc0, 0x9a, 0x1b, 0xb4, 0x26, 0x14, 0x03, 0x54, 0x8d, 0xe6, 0x5a, 0x06, 0xf0, 0x3b, 0xac,
	0x40, 0x1e, 0xf2, 0xfc, 0xda, 0x10, 0x99, 0x16, 0x54, 0x84, 0xca, 0xfe, 0x53, 0x0d, 0x5e, 0x3b,
	0x07, 0x3e, 0x8c, 0x9a, 0xf9, 0x83, 0x41, 0x6e, 0xfa, 0x52, 0x56, 0xd4, 0xa9, 0x6e, 0x40, 0xde,
	0xd2, 0xa0, 0x0c, 0xad, 0xe3, 0xe7, 0x7a, 0xa7, 0x5b, 0xac, 0x35, 0x93, 0x0f, 0xea, 0xff, 0x39,
	0x72, 0xcb, 0x17, 0x31, 0x7b, 0x02, 0x7e, 0xdb, 0x1f, 0x94, 0xc3, 0x57, 0x0f, 0x81, 0xb3, 0x47,
	0x31, 0x21, 0x07, 0xb6, 0xc0, 0xfa, 0x32, 0x59, 0x24, 0xab, 0xb3, 0xbb, 0x2b, 0x39, 0x96, 0xcb,
	0xbf, 0x72, 0xf9, 0xca, 0x1e, 0xad, 0x79, 0xd7, 0x6d, 0x0f, 0x9b, 0xf4, 0xe7, 0xfb, 0xe6, 0x64,
	0x91, 0xe4, 0xe9, 0x1e, 0x7a, 0xae, 0x97, 0x2b, 0x71, 0x7e, 0x34, 0x06, 0x47, 0x36, 0x40, 0x76,
	0x21, 0x4e, 0xe3, 0xe6, 0x28, 0x9c, 0xe6, 0x63, 0xd8, 0x4c, 0x3f, 0x26, 0x87, 0x79, 0x65, 0x1a,
	0xd5, 0xf7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x71, 0xb1, 0x37, 0xeb, 0x1f, 0x01, 0x00, 0x00,
}
