// Code generated by protoc-gen-go. DO NOT EDIT.
// source: get_wechat_session.proto

package wechatd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetWechatSessionRequest struct {
	JsCode               *wrappers.StringValue `protobuf:"bytes,1,opt,name=js_code,json=jsCode" json:"js_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetWechatSessionRequest) Reset()         { *m = GetWechatSessionRequest{} }
func (m *GetWechatSessionRequest) String() string { return proto.CompactTextString(m) }
func (*GetWechatSessionRequest) ProtoMessage()    {}
func (*GetWechatSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_get_wechat_session_a42a26d969e7353e, []int{0}
}
func (m *GetWechatSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWechatSessionRequest.Unmarshal(m, b)
}
func (m *GetWechatSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWechatSessionRequest.Marshal(b, m, deterministic)
}
func (dst *GetWechatSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWechatSessionRequest.Merge(dst, src)
}
func (m *GetWechatSessionRequest) XXX_Size() int {
	return xxx_messageInfo_GetWechatSessionRequest.Size(m)
}
func (m *GetWechatSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWechatSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWechatSessionRequest proto.InternalMessageInfo

func (m *GetWechatSessionRequest) GetJsCode() *wrappers.StringValue {
	if m != nil {
		return m.JsCode
	}
	return nil
}

type GetWechatSessionResponse struct {
	OpenId               string   `protobuf:"bytes,1,opt,name=open_id,json=openId" json:"open_id,omitempty"`
	SessionKey           string   `protobuf:"bytes,2,opt,name=session_key,json=sessionKey" json:"session_key,omitempty"`
	UnionId              string   `protobuf:"bytes,3,opt,name=union_id,json=unionId" json:"union_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWechatSessionResponse) Reset()         { *m = GetWechatSessionResponse{} }
func (m *GetWechatSessionResponse) String() string { return proto.CompactTextString(m) }
func (*GetWechatSessionResponse) ProtoMessage()    {}
func (*GetWechatSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_get_wechat_session_a42a26d969e7353e, []int{1}
}
func (m *GetWechatSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWechatSessionResponse.Unmarshal(m, b)
}
func (m *GetWechatSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWechatSessionResponse.Marshal(b, m, deterministic)
}
func (dst *GetWechatSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWechatSessionResponse.Merge(dst, src)
}
func (m *GetWechatSessionResponse) XXX_Size() int {
	return xxx_messageInfo_GetWechatSessionResponse.Size(m)
}
func (m *GetWechatSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWechatSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWechatSessionResponse proto.InternalMessageInfo

func (m *GetWechatSessionResponse) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *GetWechatSessionResponse) GetSessionKey() string {
	if m != nil {
		return m.SessionKey
	}
	return ""
}

func (m *GetWechatSessionResponse) GetUnionId() string {
	if m != nil {
		return m.UnionId
	}
	return ""
}

func init() {
	proto.RegisterType((*GetWechatSessionRequest)(nil), "ai.metathings_wechatd.service.wechatd.GetWechatSessionRequest")
	proto.RegisterType((*GetWechatSessionResponse)(nil), "ai.metathings_wechatd.service.wechatd.GetWechatSessionResponse")
}

func init() {
	proto.RegisterFile("get_wechat_session.proto", fileDescriptor_get_wechat_session_a42a26d969e7353e)
}

var fileDescriptor_get_wechat_session_a42a26d969e7353e = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xc1, 0x4b, 0xfb, 0x30,
	0x14, 0xc7, 0xe9, 0x7e, 0xd0, 0xfe, 0xcc, 0x6e, 0xbd, 0xac, 0x0e, 0x71, 0x63, 0x20, 0x78, 0x59,
	0x0a, 0x0a, 0xde, 0xbc, 0xe8, 0x41, 0x86, 0xb7, 0x0e, 0xd4, 0x5b, 0x49, 0x9b, 0x67, 0x9a, 0xad,
	0xcd, 0xab, 0x79, 0xe9, 0xca, 0xfe, 0x5a, 0xc1, 0xbf, 0x44, 0x96, 0x56, 0x2f, 0xde, 0xf2, 0xcd,
	0x27, 0xef, 0x9b, 0x0f, 0x8f, 0x25, 0x0a, 0x5c, 0xde, 0x43, 0x59, 0x09, 0x97, 0x13, 0x10, 0x69,
	0x34, 0xbc, 0xb5, 0xe8, 0x30, 0xbe, 0x12, 0x9a, 0x37, 0xe0, 0x84, 0xab, 0xb4, 0x51, 0x34, 0xbe,
	0x91, 0x9c, 0xc0, 0x1e, 0x74, 0x09, 0x7c, 0xcc, 0xf3, 0x4b, 0x85, 0xa8, 0x6a, 0x48, 0xfd, 0x50,
	0xd1, 0xbd, 0xa7, 0xbd, 0x15, 0x6d, 0x0b, 0x96, 0x86, 0x9a, 0xf9, 0x9d, 0xd2, 0xae, 0xea, 0x0a,
	0x5e, 0x62, 0x93, 0x36, 0xbd, 0x76, 0x7b, 0xec, 0x53, 0x85, 0x6b, 0x0f, 0xd7, 0x07, 0x51, 0x6b,
	0x29, 0x1c, 0x5a, 0x4a, 0x7f, 0x8f, 0xc3, 0xdc, 0xea, 0x8d, 0xcd, 0x9e, 0xc0, 0xbd, 0xfa, 0x5f,
	0xb6, 0x83, 0x58, 0x06, 0x1f, 0x1d, 0x90, 0x8b, 0xef, 0x59, 0xb4, 0xa3, 0xbc, 0x44, 0x09, 0x49,
	0xb0, 0x0c, 0xae, 0xa7, 0x37, 0x17, 0x7c, 0x90, 0xe0, 0x3f, 0x12, 0x7c, 0xeb, 0xac, 0x36, 0xea,
	0x45, 0xd4, 0x1d, 0x3c, 0x84, 0x5f, 0x9f, 0x8b, 0xc9, 0x32, 0xc8, 0xc2, 0x1d, 0x3d, 0xa2, 0x84,
	0x15, 0xb2, 0xe4, 0x6f, 0x33, 0xb5, 0x68, 0x08, 0xe2, 0x19, 0x8b, 0xb0, 0x05, 0x93, 0x6b, 0xe9,
	0xab, 0xcf, 0xb2, 0xf0, 0x14, 0x37, 0x32, 0x5e, 0xb0, 0xe9, 0xb8, 0x9e, 0x7c, 0x0f, 0xc7, 0x64,
	0xe2, 0x21, 0x1b, 0xaf, 0x9e, 0xe1, 0x18, 0x9f, 0xb3, 0xff, 0x9d, 0x39, 0x61, 0x2d, 0x93, 0x7f,
	0x9e, 0x46, 0x3e, 0x6f, 0x64, 0x11, 0x7a, 0xad, 0xdb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1a,
	0xbd, 0x3d, 0x6a, 0x6c, 0x01, 0x00, 0x00,
}
