// Code generated by protoc-gen-go. DO NOT EDIT.
// source: get_session.proto

package wechatd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetSessionRequest struct {
	JsCode               *wrappers.StringValue `protobuf:"bytes,1,opt,name=js_code,json=jsCode" json:"js_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetSessionRequest) Reset()         { *m = GetSessionRequest{} }
func (m *GetSessionRequest) String() string { return proto.CompactTextString(m) }
func (*GetSessionRequest) ProtoMessage()    {}
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_get_session_ee4bcb7cb0a05e12, []int{0}
}
func (m *GetSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionRequest.Unmarshal(m, b)
}
func (m *GetSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionRequest.Marshal(b, m, deterministic)
}
func (dst *GetSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionRequest.Merge(dst, src)
}
func (m *GetSessionRequest) XXX_Size() int {
	return xxx_messageInfo_GetSessionRequest.Size(m)
}
func (m *GetSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionRequest proto.InternalMessageInfo

func (m *GetSessionRequest) GetJsCode() *wrappers.StringValue {
	if m != nil {
		return m.JsCode
	}
	return nil
}

type GetSessionResponse struct {
	OpenId               string   `protobuf:"bytes,1,opt,name=open_id,json=openId" json:"open_id,omitempty"`
	SessionKey           string   `protobuf:"bytes,2,opt,name=session_key,json=sessionKey" json:"session_key,omitempty"`
	UnionId              string   `protobuf:"bytes,3,opt,name=union_id,json=unionId" json:"union_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSessionResponse) Reset()         { *m = GetSessionResponse{} }
func (m *GetSessionResponse) String() string { return proto.CompactTextString(m) }
func (*GetSessionResponse) ProtoMessage()    {}
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_get_session_ee4bcb7cb0a05e12, []int{1}
}
func (m *GetSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionResponse.Unmarshal(m, b)
}
func (m *GetSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionResponse.Marshal(b, m, deterministic)
}
func (dst *GetSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionResponse.Merge(dst, src)
}
func (m *GetSessionResponse) XXX_Size() int {
	return xxx_messageInfo_GetSessionResponse.Size(m)
}
func (m *GetSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionResponse proto.InternalMessageInfo

func (m *GetSessionResponse) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *GetSessionResponse) GetSessionKey() string {
	if m != nil {
		return m.SessionKey
	}
	return ""
}

func (m *GetSessionResponse) GetUnionId() string {
	if m != nil {
		return m.UnionId
	}
	return ""
}

func init() {
	proto.RegisterType((*GetSessionRequest)(nil), "ai.metathings_wechatd.service.wechatd.GetSessionRequest")
	proto.RegisterType((*GetSessionResponse)(nil), "ai.metathings_wechatd.service.wechatd.GetSessionResponse")
}

func init() { proto.RegisterFile("get_session.proto", fileDescriptor_get_session_ee4bcb7cb0a05e12) }

var fileDescriptor_get_session_ee4bcb7cb0a05e12 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xd9, 0x84, 0x4e, 0xb3, 0xd3, 0x72, 0xb1, 0x0e, 0x71, 0x63, 0x20, 0x78, 0x59, 0x0a,
	0x0a, 0xde, 0xbc, 0xe8, 0x41, 0x86, 0xb7, 0x0e, 0xbc, 0x96, 0xb4, 0x79, 0xa6, 0xd9, 0xda, 0xbc,
	0x9a, 0x97, 0xae, 0xec, 0xaf, 0x15, 0xfc, 0x4b, 0x64, 0x69, 0x15, 0x6f, 0xf9, 0xe6, 0xc3, 0xf7,
	0x07, 0x8f, 0xcd, 0x34, 0xf8, 0x8c, 0x80, 0xc8, 0xa0, 0x15, 0x8d, 0x43, 0x8f, 0xfc, 0x56, 0x1a,
	0x51, 0x83, 0x97, 0xbe, 0x34, 0x56, 0x53, 0xd6, 0x41, 0x51, 0x4a, 0xaf, 0x04, 0x81, 0x3b, 0x98,
	0x02, 0xc4, 0xa0, 0xe7, 0x37, 0x1a, 0x51, 0x57, 0x90, 0x04, 0x53, 0xde, 0x7e, 0x24, 0x9d, 0x93,
	0x4d, 0x03, 0x8e, 0xfa, 0x98, 0xf9, 0xa3, 0x36, 0xbe, 0x6c, 0x73, 0x51, 0x60, 0x9d, 0xd4, 0x9d,
	0xf1, 0x7b, 0xec, 0x12, 0x8d, 0xeb, 0x00, 0xd7, 0x07, 0x59, 0x19, 0x25, 0x3d, 0x3a, 0x4a, 0xfe,
	0x9e, 0xbd, 0x6f, 0x95, 0xb2, 0xd9, 0x2b, 0xf8, 0x6d, 0x3f, 0x29, 0x85, 0xcf, 0x16, 0xc8, 0xf3,
	0x27, 0x36, 0xd9, 0x51, 0x56, 0xa0, 0x82, 0x78, 0xb4, 0x1c, 0xdd, 0x4d, 0xef, 0xaf, 0x45, 0x5f,
	0x2f, 0x7e, 0xeb, 0xc5, 0xd6, 0x3b, 0x63, 0xf5, 0xbb, 0xac, 0x5a, 0x78, 0x8e, 0xbe, 0xbf, 0x16,
	0xe3, 0xe5, 0x28, 0x8d, 0x76, 0xf4, 0x82, 0x0a, 0x56, 0x86, 0xf1, 0xff, 0x99, 0xd4, 0xa0, 0x25,
	0xe0, 0x97, 0x6c, 0x82, 0x0d, 0xd8, 0xcc, 0xa8, 0x10, 0x7a, 0x91, 0x46, 0x27, 0xb9, 0x51, 0x7c,
	0xc1, 0xa6, 0xc3, 0x49, 0xb2, 0x3d, 0x1c, 0xe3, 0x71, 0x80, 0x6c, 0xf8, 0x7a, 0x83, 0x23, 0xbf,
	0x62, 0xe7, 0xad, 0x3d, 0x61, 0xa3, 0xe2, 0xb3, 0x40, 0x27, 0x41, 0x6f, 0x54, 0x1e, 0x85, 0x41,
	0x0f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x64, 0x0b, 0xcb, 0x59, 0x01, 0x00, 0x00,
}
