// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: get_session.proto

/*
Package wechatd is a generated protocol buffer package.

It is generated from these files:
	get_session.proto
	get_token.proto
	service.proto

It has these top-level messages:
	GetSessionRequest
	GetSessionResponse
	GetTokenRequest
	GetTokenResponse
*/
package wechatd

import fmt "fmt"
import go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import math "math"
import _ "github.com/golang/protobuf/ptypes/wrappers"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *GetSessionRequest) Validate() error {
	if nil == this.JsCode {
		return go_proto_validators.FieldError("JsCode", fmt.Errorf("message must exist"))
	}
	if this.JsCode != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.JsCode); err != nil {
			return go_proto_validators.FieldError("JsCode", err)
		}
	}
	return nil
}
func (this *GetSessionResponse) Validate() error {
	return nil
}
