// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package wechatd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WechatdService service

type WechatdServiceClient interface {
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error)
}

type wechatdServiceClient struct {
	cc *grpc.ClientConn
}

func NewWechatdServiceClient(cc *grpc.ClientConn) WechatdServiceClient {
	return &wechatdServiceClient{cc}
}

func (c *wechatdServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	out := new(GetSessionResponse)
	err := grpc.Invoke(ctx, "/ai.metathings_wechatd.service.wechatd.WechatdService/GetSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wechatdServiceClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	out := new(GetTokenResponse)
	err := grpc.Invoke(ctx, "/ai.metathings_wechatd.service.wechatd.WechatdService/GetToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WechatdService service

type WechatdServiceServer interface {
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error)
}

func RegisterWechatdServiceServer(s *grpc.Server, srv WechatdServiceServer) {
	s.RegisterService(&_WechatdService_serviceDesc, srv)
}

func _WechatdService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WechatdServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.metathings_wechatd.service.wechatd.WechatdService/GetSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WechatdServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WechatdService_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WechatdServiceServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.metathings_wechatd.service.wechatd.WechatdService/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WechatdServiceServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WechatdService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ai.metathings_wechatd.service.wechatd.WechatdService",
	HandlerType: (*WechatdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSession",
			Handler:    _WechatdService_GetSession_Handler,
		},
		{
			MethodName: "GetToken",
			Handler:    _WechatdService_GetToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_fe328b8104e93907) }

var fileDescriptor_service_fe328b8104e93907 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x52, 0x4d, 0xcc, 0xd4, 0xcb, 0x4d,
	0x2d, 0x49, 0x2c, 0xc9, 0xc8, 0xcc, 0x4b, 0x2f, 0x8e, 0x2f, 0x4f, 0x4d, 0xce, 0x48, 0x2c, 0x49,
	0xd1, 0x83, 0x29, 0x82, 0xf2, 0xa5, 0x04, 0xd3, 0x53, 0x4b, 0xe2, 0x8b, 0x53, 0x8b, 0x8b, 0x33,
	0xf3, 0xf3, 0x20, 0x3a, 0xa5, 0xf8, 0x41, 0x42, 0x25, 0xf9, 0xd9, 0xa9, 0x50, 0x01, 0xa3, 0xa9,
	0x4c, 0x5c, 0x7c, 0xe1, 0x10, 0xf5, 0xc1, 0x10, 0xed, 0x42, 0xcd, 0x8c, 0x5c, 0x5c, 0xee, 0xa9,
	0x25, 0xc1, 0x10, 0x8d, 0x42, 0x16, 0x7a, 0x44, 0xd9, 0xa6, 0x87, 0xd0, 0x12, 0x94, 0x5a, 0x58,
	0x9a, 0x5a, 0x5c, 0x22, 0x65, 0x49, 0x86, 0xce, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x25, 0x06,
	0xa1, 0x5a, 0x2e, 0x0e, 0xf7, 0xd4, 0x92, 0x10, 0x90, 0x53, 0x85, 0xcc, 0x88, 0x37, 0x08, 0xac,
	0x01, 0xe6, 0x00, 0x73, 0x92, 0xf5, 0xc1, 0xac, 0x77, 0xe2, 0x8c, 0x62, 0x87, 0xca, 0x26, 0xb1,
	0x81, 0x43, 0xca, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x82, 0x26, 0xbc, 0x85, 0x01, 0x00,
	0x00,
}
